### ISSUE TITLE
使用idea打开缺少依赖报错

### ISSUE THREAD

**Issue by coffee-developer** [FJ-OMS/oms-erp#4]
![image](https://user-images.githubusercontent.com/35052485/209918472-51d30cf6-a072-4fe2-80b6-02c46d711105.png)
![image](https://user-images.githubusercontent.com/35052485/209918525-d995defb-568b-4f50-815c-aeb3308ae353.png)
项目无法启动,缺少一些自定义jar包,maven公共仓库也没有的

**Comment by FJ-OMS** [comment]
咨询我们技术微信Blowbing
